// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package internal

import (
	"context"
)

type Querier interface {
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	GetSale(ctx context.Context, id int64) (Sale, error)
	GetSaleForUpdate(ctx context.Context, id int64) (Sale, error)
	ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error)
}

var _ Querier = (*Queries)(nil)
